modLoader = "${modLoader}"
loaderVersion = "${loaderVersion}"
issueTrackerURL = "${issueTrackerURL}"
license = "${license}"

[[mixins]]
    config = "${mod_id}.mixins.json"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "logo.png"
    itemIcon = "windswept:holly_wreath"
    configBackground = "windswept:textures/block/holly_log.png"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/windsweptmod"
    authors = "Rose, Yape"
    description = '''Windswept is a vanilla-esque mod that vastly expands colder regions of the game. It adds new biomes such as Tundras, Pine Barrens, Chestnut Forests, Lavender Fields, and Flowering Savannas, along with new flowers, enemies, and much more—basically a whole bunch of content related to winter!'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${mc_version}]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "blueprint"
    type = "required"
    versionRange = "[${blueprint},)"
    ordering = "AFTER"
    side = "BOTH"